#!/bin/sh
echo '#!/bin/sh' > co.all
echo co -u jcpp make* COPYING *.html *.java */*.java */*.j >> co.all
chmod a+x co.all

echo '#!/bin/sh' > compile
echo 'COMPILER=${1:-javac}' >> compile
echo 'if [ -z "$1" ]; then FLAGS="-g"; else shift; FLAGS="$*"; fi' >>compile
echo 'rm -f *.class */*.class' >> compile
echo 'jasmin -d .. jvm/Interpreter.j' >> compile
echo \$COMPILER \$FLAGS -d .. Decompiler.java Obfuscator.java JodeApplet.java swingui/MainWindow.java >> compile
chmod a+x compile
./compile jikes -g

cd ..
DATE=`date +"%Y%m%d"`
tar -cvzf jode/jode-RCS-$DATE.tar.gz \
    jode/co.all jode/compile jode/RCS jode/*/RCS

zip jode/jode-$DATE.zip \
    jode/COPYING jode/*.html jode/jcpp \
    jode/*.java jode/*/*.java jode/*.class jode/*/*.class
