#!/bin/sh
echo '#!/bin/sh' > co.all
echo co -u jcpp make* COPYING *.html *.java */*.java */*.j >> co.all
chmod a+x co.all

echo '#!/bin/sh' > compile
echo 'COMPILER=${1:-javac}' >> compile
echo 'if [ -z "$1" ]; then FLAGS="-g"; else shift; FLAGS="$*"; fi' >>compile
echo 'rm -f *.class */*.class' >> compile
echo 'jasmin -d .. jvm/Interpreter.j' >> compile
echo \$COMPILER \$FLAGS -d .. Decompiler.java obfuscator/Main.java JodeApplet.java swingui/Main.java >> compile
chmod a+x compile

cd ..
tar -cvzf jode/jode.tar.gz jode/co.all jode/compile jode/RCS jode/*/RCS
