</td></tr>
</table>
<TABLE width="100%" border="0" cellspacing="0" cellpadding="2" bgcolor="737b9c">
  <TR>
    <TD align="center"><FONT color="#ffffff"><SPAN class="titlebar">
      All trademarks and copyrights on this page are properties of their respective owners. <br>
      Last updated on 30-Jun-2000, 
	Copyright &copy; 1998-2000 by Jochen Hoenicke.</SPAN></FONT>
    </TD>
  </TR>
</TABLE>

</BODY>
</HTML>
