#!/bin/sh

if [ ! -e GlobalOptions.java ]; then
    echo "Please cd to the jode directory first."
    exit 1
fi

DATE=`date +"%Y%m%d"`
perl -i -pe's/(snapshot )[0-9]+/${1}'$DATE'/
            if /public final static String version/;'  GlobalOptions.java

./ci.all
echo '#!/bin/sh' > co.all
echo co -u jcpp make* COPYING *.html *.java */*.java */*.j >> co.all
chmod a+x co.all

echo '#!/bin/sh' > compile
echo 'COMPILER=${1:-javac}' >> compile
echo 'if [ -z "$1" ]; then FLAGS="-g"; else shift; FLAGS="$*"; fi' >>compile
echo 'rm -f *.class */*.class' >> compile
echo 'jasmin -d .. jvm/Interpreter.j' >> compile
echo \$COMPILER \$FLAGS -d .. Decompiler.java Obfuscator.java JodeApplet.java swingui/MainWindow.java >> compile
chmod a+x compile
./compile jikes -g

cd ..
tar -cvzf jode/snapshot/jode-RCS-$DATE.tar.gz \
    jode/co.all jode/compile jode/RCS jode/*/RCS

zip jode/snapshot/jode-$DATE.zip \
    jode/COPYING jode/*.html jode/jcpp \
    jode/*.java jode/*/*.java jode/*/*.j jode/*.class jode/*/*.class
